[package]
name = "bricklayers"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
env_logger = "0.11.6"
log = "0.4.25"
once_cell = "1.20.2"
regex = "1.11.1"
